const ItemFiltersTypes = {
  GET_FILTERS: 'GET_FILTERS',
  FETCH_FILTERS: 'FETCH_FILTERS',
  FETCH_FILTERS_START: 'FETCH_FILTERS_START',
  FETCH_FILTERS_SUCCESS: 'FETCH_FILTERS_SUCESS',
  FETCH_FILTERS_ERROR: 'FETCH_FILTERS_ERROR',
  SET_ACTIVE_FILTERS: 'SET_ACTIVE_FILTERS',
  SET_SELECTED_FILTERS: 'SET_SELECTED_FILTERS',
}

export default ItemFiltersTypes
