const ItemListTypes = {
  FETCH_ITEMS_START: 'FETCH_ITEMS_START',
  FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCESS',
  FETCH_ITEMS_ERROR: 'FETCH_ITEMS_ERROR',
  SET_ACTIVE_FILTERS: 'SET_ACTIVE_FILTERS',
  SET_SELECTED_FILTERS: 'SET_SELECTED_FILTERS',
}

export default ItemListTypes
