const AssessmentTypes = {
  ASSESSSMENT_INIT: 'ASSESSSMENT_INIT',
  ASSESSSMENT_READY: 'ASSESSSMENT_READY',
  FETCH_ASSESSMENT: 'FETCH_ASSESSMENT',
  FETCH_ASSESSMENT_START: 'FETCH_ASSESSMENT_START',
  FETCH_ASSESSMENT_SUCCESS: 'FETCH_ASSESSMENT_SUCESS',
  FETCH_ASSESSMENT_ERROR: 'FETCH_ASSESSMENT_ERROR',
}

export default AssessmentTypes
