const AssessmentTypes = {
  ASSESSSMENT_INIT: 'ASSESSSMENT_INIT',
  ASSESSSMENT_READY: 'ASSESSSMENT_READY',
  FETCH_ASSESSMENT: 'FETCH_ASSESSMENT',
  FETCH_ASSESSMENT_ERROR: 'FETCH_ASSESSMENT_ERROR',
  SET_ASSESSMENT: 'FETCH_ASSESSMENT_SUCESS',
  SET_ASSESSMENT_QUESTIONS: 'SET_ASSESSMENT_QUESTIONS',
}

export default AssessmentTypes
